# Generated by Django 3.2.9 on 2021-11-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211106_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of Followers', verbose_name='Followers Count'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of people you follow', verbose_name='Followerings Count'),
        ),
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(help_text='Posting Text', verbose_name='Post Text')),
                ('post_ts', models.DateTimeField(auto_now_add=True, verbose_name='Posting Timestamp')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes', verbose_name='Likes Count')),
                ('dislikes_count', models.PositiveIntegerField(default=0, help_text='Number of dislikes', verbose_name='Dislikes Count')),
                ('post_superceded', models.BooleanField(default=False, help_text='This post superceded by another post.', verbose_name='Superceded')),
                ('supercede_ts', models.DateTimeField(verbose_name='Supercede Timestamp')),
                ('posting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', related_query_name='poster', to=settings.AUTH_USER_MODEL, verbose_name='Poster')),
                ('superceding_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suceeding_post', related_query_name='suceeding_post', to='network.postings', verbose_name='Suceeding Post')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=True, help_text='Like or Dislike', verbose_name='Likes?')),
                ('likes_active', models.BooleanField(default=True, help_text='This like is Active', verbose_name='Active Likes?')),
                ('likes_starts_ts', models.DateTimeField(verbose_name='Likes Timestamp')),
                ('likes_ends_ts', models.DateTimeField(verbose_name='Like End Timestamp')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', related_query_name='liker', to=settings.AUTH_USER_MODEL, verbose_name='Liker')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', related_query_name='liked_post', to='network.postings', verbose_name='Liked Post')),
            ],
        ),
        migrations.CreateModel(
            name='Followings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_active', models.BooleanField(default=True, help_text='The following is active.', verbose_name='Following Active')),
                ('follow_start', models.DateTimeField(auto_now_add=True, verbose_name='Following Start Timestamp')),
                ('follow_end', models.DateTimeField(verbose_name='Following End Timestamp')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', related_query_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
                ('follows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', related_query_name='follows', to=settings.AUTH_USER_MODEL, verbose_name='Follows')),
            ],
        ),
    ]
