# Generated by Django 3.2.9 on 2021-11-10 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211106_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followings',
            name='follow_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Following End Timestamp'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='likes_ends_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Like End Timestamp'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='likes_starts_ts',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Likes Timestamp'),
        ),
        migrations.AlterField(
            model_name='postings',
            name='supercede_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supercede Timestamp'),
        ),
        migrations.AlterField(
            model_name='postings',
            name='superceding_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suceeding_post', related_query_name='suceeding_post', to='network.postings', verbose_name='Suceeding Post'),
        ),
    ]
