# Generated by Django 3.2.9 on 2021-11-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20211110_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postings',
            name='superceding_post',
        ),
        migrations.AddField(
            model_name='postings',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replaced_post', related_query_name='replaced_post', to='network.postings', verbose_name='Suceeding Post'),
        ),
    ]
