# Generated by Django 3.2.9 on 2021-12-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211112_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postings',
            options={'ordering': ['id']},
        ),
    ]
